"""Extract visually reviewed question crops from the supplied MADE EASY CS sample.

This is deliberately checksum-bound: the supplied file has 18 pages, not the
805 pages listed in its contents. It includes Q1.1-1.57 and part of Q1.58.
The full book needs its own reviewed page map, not these sample coordinates.
Requires pypdfium2 and Pillow. Source material/output stay in ignored data/.
"""
import argparse
import hashlib
import json
from pathlib import Path

import pypdfium2 as pdfium
from PIL import Image, ImageDraw

SOURCE_SHA = 'd8ef1747511ef1e29d5cbe5196fc0d60082ca172677da755cd64973c05150ce1'
EDITION = 'made-easy-gate-cs-2026'
SLUG = 'made-easy-cs-finite-automata'
CHAPTER = 'Finite Automata and Regular Languages'
SCALE = 2.5
COLUMNS = [(112, 730), (765, 1375)]
# First source question in each column, and visually verified black number labels.
PAGE_LABELS = {
    7: [(1, [379, 619, 892, 1132, 1340, 1580]), (7, [453, 693, 940, 1148, 1420, 1628])],
    8: [(13, [180, 452, 757, 965, 1205, 1515]), (19, [449, 624, 1058, 1615])],
    9: [(23, [180, 647, 1079, 1319, 1527]), (28, [546, 1046, 1351])],
    10: [(31, [180, 710, 1300, 1636]), (35, [384, 871, 1046, 1221, 1559, 1734])],
    11: [(41, [318, 526, 957, 1133, 1275]), (46, [180, 925, 1459])],
    12: [(49, [1291]), (50, [711])],
    13: [(51, [180, 452, 725, 997, 1568]), (56, [180, 597, 1272])],
}
# Transcribed from the answer table on PDF page 14 (printed page 148).
KEYS = ('c d b d d a cd d b b c b d a b d d a b c b c b a b a a b d b '
        'b d a a c b a c d b a c c b a d c b a a c c a a d a a c').split()
YEARS = [1996]*2 + [1997]*2 + [1998]*5 + [1999] + [2000]*3 + [2001]*4 + [2002]*2 + [2003]*2 + [2004]*3 + [2005]*7 + [2006]*8 + [2007]*12 + [2008]*7
ONE_MARK = {1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 14, 15, 22, 25, 26, 32, 33, 40, 52, 53}
PROMPTS = [
    'Which two of the following four regular expressions are equivalent?',
    'Let L be a language over {a, b}. Which of the following is true?',
    'Given the alphabet {a, b}, which one of the following sets is not countable?',
    'Which regular expression over {0, 1} denotes strings not containing 100 as a substring?',
    'Compare the two regular sets A and B defined by the given regular expressions.',
    'Which of the following sets can be recognized by a deterministic finite state automaton?',
    'The string 1101 does not belong to the set represented by which regular expression?',
    'How many non-empty substrings can be formed from a character string of length n?',
    'Find the minimum number of DFA states for binary strings whose last two symbols are the same.',
    'Find the minimum number of states recognizing the regular expression (0 + 1) repeated n times.',
    'Compare the languages represented by (a + b*)* and (a + b)*.',
    'Classify the language generated by S -> 0S0 | 00.',
    'What can be said about a regular language over {a} whose minimal automaton has two states?',
    'Determine which of the two given statements about regular languages are correct.',
    'Find the maximum number of states in a minimized DFA equivalent to an N-state NFA.',
    'Find the minimum DFA states when the numbers of a and b are divisible by 6 and 8, respectively.',
    'Which of the four given languages are regular?',
    'Determine the output computed by the finite state machine with start state A.',
    'Find the smallest automaton accepting strings whose length is divisible by 3.',
    'Count the specified seven-bit strings accepted by the given DFA.',
    'Compare the languages when accepting and non-accepting states of the given NFA are interchanged.',
    'Which regular expression is not equivalent to (a + b + c)*?',
    'Find a grammar generating the same language as the specified finite state automaton.',
    'Determine the numbers of zeros and ones accepted by the given finite state machine.',
    'Which statement is true about the regular expression 01*0?',
    'Classify the language {0^n 1^n 2^n | 1 <= n <= 10^6}.',
    'Compare the languages accepted by the given NFA with Y or Z as its only accepting state.',
    'Find the minimum DFA states needed to recognize the given regular grammar.',
    'What follows when a language satisfies the pumping lemmas for regular and context-free languages?',
    'Determine the language recognized by the given machine M.',
    'Determine the operation performed by the binary-input finite state machine, least significant bit first.',
    'Determine which of u = abbaba, v = bab and w = aabb are accepted by the given automaton.',
    'Which regular expression describes the language accepted by the given NFA?',
    'Find the Myhill-Nerode equivalence classes of the language generated by the given grammar.',
    'Which statement about regular languages is not true?',
    'Which construction on a regular language could produce a non-regular language?',
    'Which regular language supports the preceding construction answer? Shared context is included.',
    'Which of the given languages defined using zero and one counts is not regular?',
    'Find the minimum number of DFA states for L = (111 + 11111)*.',
    'Which statement about regular sets and finite sets is true?',
    'Find the minimum DFA states when zero and one counts are divisible by 3 and 5, respectively.',
    'Which of the given languages is regular?',
    'Find a regular expression for the language of the shared finite state automaton.',
    'Find the number of states in the minimal automaton equivalent to the shared automaton.',
    'Determine the properties of strings generated by grammars G1 and G2.',
    'Determine the language recognized by the DFA with start state s0 and final states s1 and s3.',
    'Which of the six specified strings are generated by the given grammar?',
    'Choose the automaton recognizing the intersection L(P) and L(Q).',
    'Choose the NFA recognizing the shared regular expression R = (a + b)*(aa + bb)(a + b)*.',
    'Choose the DFA recognizing the shared regular expression R = (a + b)*(aa + bb)(a + b)*.',
    'Choose an equivalent regular expression for R = (a + b)*(aa + bb)(a + b)*.',
    'Which regular expression denotes binary strings containing exactly two ones?',
    'Which relation necessarily holds between an n-state NFA and its minimized m-state DFA?',
    'Determine the language after interchanging final and non-final states of the given DFA.',
    'Which of the given languages are non-regular?',
    'Compare the languages accepted by the two given finite automata.',
    'Choose the product automaton Z x Y from the given transition tables.',
    'Match the finite automata in List I with List II. The supplied PDF omits the continuation.',
]


def segment(page, column, top, bottom):
    left, right = COLUMNS[column]
    return {'page': page, 'box': [left, top, right, bottom]}


def extract(pdf_path, output, asset_dir):
    checksum = hashlib.sha256(pdf_path.read_bytes()).hexdigest()
    if checksum != SOURCE_SHA:
        raise ValueError('This page map is only for the reviewed 18-page sample. Review the new PDF before extracting it.')
    doc = pdfium.PdfDocument(str(pdf_path))
    if len(doc) != 18:
        raise ValueError('Unexpected PDF page count.')
    assert len(KEYS) == len(YEARS) == len(PROMPTS) == 58
    pages = {}
    for pn in range(7, 14):
        page = doc[pn - 1]
        bitmap = page.render(scale=SCALE)
        pages[pn] = bitmap.to_pil().copy().convert('RGB')
        bitmap.close()
        page.close()
        if pages[pn].size != (1485, 1980):
            raise ValueError('Unexpected page dimensions.')
    nodes = []
    for pn, columns in PAGE_LABELS.items():
        for col, (first, ys) in enumerate(columns):
            for offset, y in enumerate(ys):
                # Check the exact reviewed black label before using its coordinates.
                x = 120 if col == 0 else 771
                if any(pages[pn].getpixel((x, yy))[0] > 80 for yy in range(y + 1, y + 35)):
                    raise ValueError(f'Question label moved: page {pn}, question {first + offset}')
                nodes.append({'number': first + offset, 'page': pn, 'col': col, 'top': y - 4})
    assert [n['number'] for n in nodes] == list(range(1, 59))
    # Move the start of each first shared question to include its common data.
    shared_starts = {36: 616, 43: 700, 49: 1165}
    for node in nodes:
        node['top'] = shared_starts.get(node['number'], node['top'])
    target = asset_dir / SLUG
    target.mkdir(parents=True, exist_ok=True)
    questions = []
    for index, node in enumerate(nodes):
        following = nodes[index + 1] if index + 1 < len(nodes) else None
        start_slot = (node['page'] - 7) * 2 + node['col']
        end_slot = (following['page'] - 7) * 2 + following['col'] if following else start_slot
        segments = []
        for slot in range(start_slot, end_slot + 1):
            pn, col = 7 + slot // 2, slot % 2
            top = node['top'] if slot == start_slot else (375 if pn == 7 else 175)
            bottom = following['top'] if following and slot == end_slot else 1905
            if bottom - top > 8:
                segments.append(segment(pn, col, top, bottom))
        number = node['number']
        context = {
            37: [segment(10, 1, 616, 942)],
            44: [segment(11, 0, 700, 953)],
            50: [segment(12, 0, 1165, 1287)],
            51: [segment(12, 0, 1165, 1287)],
        }.get(number, [])
        segments = context + segments
        source_id = hashlib.sha256(f'{EDITION}:theory-of-computation:1.{number}'.encode()).hexdigest()[:24]
        reasons = []
        if number == 7:
            reasons.append('Printed MCQ answer key lists both (c) and (d); verify accepted-answer semantics before publishing.')
        if number == 58:
            reasons.append('Incomplete source question: continuation, List II and answer options are absent from the supplied PDF.')
        images = []
        for part, crop in enumerate(segments, 1):
            artwork = pages[crop['page']].crop(crop['box'])
            filename = f'{source_id}-{part}.webp'
            artwork.save(target / filename, format='WEBP', lossless=True)
            images.append({'url': f'/question-media/{SLUG}/{filename}', 'width': artwork.width, 'height': artwork.height})
            artwork.close()
        marks = 1 if number in ONE_MARK else 2
        questions.append({
            'sourceId': source_id, 'sourcePage': node['page'], 'printedPage': node['page'] + 126,
            'sourceQuestionNumber': number, 'sourceLabel': f'1.{number}',
            'sourceMarker': f'GATE {YEARS[index]} | {marks} M | MADE EASY CS 2026 Q1.{number}',
            'sourceAnswer': ', '.join(KEYS[index]), 'answerKeyPage': 14,
            'chapter': CHAPTER, 'chapterOrder': 1, 'questionText': PROMPTS[index],
            'questionType': 'mcq', 'options': [f'Option {letter}' for letter in ('ABCDE' if number == 48 else 'ABCD')],
            'correctAnswer': ord(KEYS[index]) - ord('a') if len(KEYS[index]) == 1 and number != 58 else None,
            'marks': marks, 'negativeMarks': 0, 'year': YEARS[index], 'examName': 'GATE',
            'questionImages': images, 'segments': segments,
            'requiresReview': bool(reasons), 'reviewReasons': reasons,
            'explanation': '', 'solutionType': 'none',
        })
    payload = {
        'version': 1, 'sourceEdition': EDITION, 'sourceName': 'MADE EASY GATE 2026 Computer Science & IT - Previous Solved Papers',
        'sourceFile': pdf_path.name, 'sourceSha256': checksum, 'sourcePages': len(doc),
        'branchCode': 'CS', 'subjectName': 'Theory of Computation', 'chapterName': CHAPTER, 'slug': SLUG,
        'coverage': {'completeQuestions': 57, 'partialQuestions': ['1.58'], 'printedQuestionPages': [133, 139],
                     'missingPrintedQuestionPages': [140, 147], 'answerKeyPrintedPage': 148,
                     'note': '18-page sample only. Other chapters and the remainder of this chapter are not included.'},
        'questions': questions,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=True), encoding='utf8')
    # Contact sheets cover every final crop, including continuation/context images.
    thumbs = []
    for q in questions:
        for part, img in enumerate(q['questionImages'], 1):
            with Image.open(asset_dir / img['url'].removeprefix('/question-media/')) as im:
                thumb = im.copy()
                thumb.thumbnail((305, 940))
                thumbs.append((f"Q{q['sourceLabel']} part {part}", thumb))
    for offset in range(0, len(thumbs), 12):
        batch = thumbs[offset:offset + 12]
        row_heights = [max(th.height for _, th in batch[i:i + 4]) + 45 for i in range(0, len(batch), 4)]
        canvas = Image.new('RGB', (1280, sum(row_heights)), '#e0e0e0')
        draw = ImageDraw.Draw(canvas)
        for pos, (label, thumb) in enumerate(batch):
            x, y = pos % 4 * 320, sum(row_heights[:pos // 4])
            draw.text((x + 6, y + 5), label, fill='black')
            canvas.paste(thumb, (x + 5, y + 27))
        canvas.save(output.parent / f'crop-review-{offset // 12 + 1}.png')
    for im in pages.values():
        im.close()
    doc.close()
    print(json.dumps({'questions': len(questions), 'ready': sum(not q['requiresReview'] for q in questions),
                      'review': sum(q['requiresReview'] for q in questions), 'images': sum(len(q['questionImages']) for q in questions),
                      'output': str(output)}))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--pdf', required=True, type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parent.parent / 'data/made-easy-cs/questions.json')
    parser.add_argument('--asset-dir', type=Path, default=Path(__file__).resolve().parent.parent / 'data/question-media')
    args = parser.parse_args()
    extract(args.pdf, args.output, args.asset_dir)
